### ISSUE TITLE
Sponsors Page

### ISSUE THREAD

**Issue by ilyasvali** [rLoopTeam/website-v2#13]
new page to be added and tab on the Nav bar - Sponsors

**Comment by ilyasvali** [comment]
any update on  this?
reference site - http://www.delfthyperloop.nl/#!partners/zlwv3

**Comment by UltraL0rd** [comment]
I'll probably do it tonight, just not sure what to put in as sponsors

**Comment by ilyasvali** [comment]
![arxpax-web-logo-small-jpg](https://cloud.githubusercontent.com/assets/17201445/14526050/b26502f0-0238-11e6-86e8-e359f6cde00c.jpg)
![fusion-360](https://cloud.githubusercontent.com/assets/17201445/14526051/b2687fe8-0238-11e6-867f-80b81b0828d8.jpg)
![mcnichols-all elements](https://cloud.githubusercontent.com/assets/17201445/14526052/b26903fa-0238-11e6-8d52-bc070bc36e08.jpg)
![r logo hrz](https://cloud.githubusercontent.com/assets/17201445/14526053/b26b9278-0238-11e6-99df-2a6224b029f5.jpg)

**Comment by UltraL0rd** [comment]
Done for now. Please note I'm no web designer, i'm actually server side, so going to need a css guy to clean everything up

**Comment by ilyasvali** [comment]
![ansys_logo](https://cloud.githubusercontent.com/assets/17201445/14583223/0b0eb5a0-0413-11e6-8e1c-e5c2a8be1564.png)

**Comment by gordon13** [comment]
Merged but not yet enabled. The link in the navbar is hidden and when the CSS is done, we can reenable it.

**Comment by gkorgood** [comment]
What still needs to be done on this?

**Comment by gordon13** [comment]
It just needs some nice styling.

**Comment by ilyasvali** [comment]
Gents I need to make live the sponsors page, can I get a update on were we at with this please?

**Comment by gordon13** [comment]
Done
