### ISSUE TITLE
http://rloop.org/team

### ISSUE THREAD

**Issue by ilyasvali** [rLoopTeam/website-v2#17]
update team page - with all memebers listed below

task 1
1.  Update social media lead
Ashley Makay - Canada
https://drive.google.com/open?id=0ByTBMElXXJG9Q2hfakRQWmRXY2M
1. Update team members

a) Jasper_Beckers_mech - Netherlands
https://drive.google.com/open?id=0BwNfHq_1FTp6cTVZVm5XZFp1bWc

Chris_Smith_Aero - USA
https://drive.google.com/open?id=0B5ZXziwXsfcdOEZ0cEEyeElnSjA

DartKen_Poon_Aero
https://drive.google.com/open?id=0B4uicJerFhrfNUZ1dU0tYUJrVms

Corey_Stein_Aero
https://drive.google.com/open?id=0B3Zv-z7NL_I2NHNDRmtpVHN0ZnM

 Peter_Stephan_Gschladt - Germany
https://drive.google.com/open?id=0B5nme-PJ0JzWRnQ2ZDNDRXNMREU

Kevin_Miller_Aero/Mech - USA
https://drive.google.com/open?id=0BynH1WLAhYTGS1RlQnBwcjMwVzA

Clarence Akagu Mech - Nigeria
https://drive.google.com/open?id=0ByTBMElXXJG9WHlpVTdHYkYxdFU

michael_elmore_numsim - USA
https://drive.google.com/open?id=0B-jbwYOIjTytV1djZ0pXLWdFZ0U

Jenico_J_NumSim - India
https://drive.google.com/open?id=0B5vojbL-4OMQWTZmd2VfWHpjblk

lachlan_grogan_systems - Australia
https://drive.google.com/open?id=0B8eWgH3l5E2LZ0cxSXVjMmt2akE

Alan_Espinoza_EngSystems - USA
https://drive.google.com/open?id=0B9L3weauaUMGT1pYM29FREh0V1E

Jari_van der Salm_MFG/Finance - Holland
https://drive.google.com/open?id=0B0IWpcw8U840R0ZJSEtUYklHVkU

Gopal_Bidari_Video - USA
https://drive.google.com/open?id=0B-cHT6GEr0fZUHYwb24yNjdHazg

cody_huang_elec - USA
https://drive.google.com/open?id=0B__Oz2MP_r8YdGRIWjFWNFZCU0E

denis_tudor_elec - Romania
https://drive.google.com/open?id=0B5CvmK-zagQgejF4Unh4bm1TT00

Cihan_Bebek_WebDev - Finland
https://drive.google.com/open?id=0B8ViQ9Z_EBJjc210b2MxU05uOVU

Matthew_Marshall_Finance - Canada
https://drive.google.com/open?id=0BxwQLRu-6naza1NqNTdBXzlsMzQ

Alex_Hale_PR_SM - UK
https://drive.google.com/open?id=0B2ZUpjC0rKBiX3JxQmYzM3UzbDg

Nathaniel_Thompson_PR
https://drive.google.com/open?id=0B8NdRNUeXWuHa2piUlI4M3ZoaE0

Ralph_Steenblik MFG-PR - 
https://drive.google.com/open?id=0BzkqgNNx7PCSeXBfeWxhTFhwd0k

matt_malcolm_PR - New Zealand
https://drive.google.com/open?id=0ByhCyef9WfSgMHF6d1gyVmYwX2s
# 

Cant find
Joseph_Cirnigliaro_ELEC-MFG
https://drive.google.com/open?id=0B94ONfmQ0MA5NjlXN3JhOFFMR00

**Comment by UltraL0rd** [comment]
This has been done, just waiting for push permissions.
The headshots will be done this weekend (unless someone can get them done earlier)

**Comment by gkorgood** [comment]
task completed, waiting on pull request to be confirmed. hoping for a flawless merge

**Comment by gordon13** [comment]
Merged
