### ISSUE TITLE
Team Page

### ISSUE THREAD

**Issue by ilyasvali** [rLoopTeam/website-v2#19]
amends
Dart Ken Poon
Aerodynamics, China (add location)

Corey Stein
Aerodynamics, USA (add location)

Ralph Steenblik
Public Relations, USA (add location)

Joseph Cirnigliaro
Electrical/Manufacturing, USA? (remove ?)

**Comment by ilyasvali** [comment]
Nathaniel Thompson
Public Relations, USA (add location)

**Comment by gkorgood** [comment]
are these locations known to be correct?

**Comment by ilyasvali** [comment]
yes based on time zone or responses

**Comment by ilyasvali** [comment]
some other amends; 

Jari van der Salm
Finance, Holland ( change to Netherlands)

Alex Hale
Public Relations, United Kingdom (change to UK)

**Comment by gkorgood** [comment]
Taken care of, as well as Clarence's role (updated from Mechanical to Mechanical/Manufacturing)
