### ISSUE TITLE
INDIEGOGO POP UP

### ISSUE THREAD

**Issue by brentenebros** [rLoopTeam/website-v2#2]
need a very simple pop up, just needs to say:

"Our campaign is live on IndieGoGo! Join us in making the future of transportation a reality!"
bit.ly/rLoopIGG
Share our campaign - every bit helps!
<facebook share> <twitter share> <youtube link>"

similar to attached pic:

![capture](https://cloud.githubusercontent.com/assets/13357722/13610632/a1a0c4d2-e52c-11e5-9790-df3d5b04d8c8.JPG)

**Comment by gordon13** [comment]
Popup is done. We can make additional styling tweaks as they come
