### ISSUE TITLE
Team Leads section

### ISSUE THREAD

**Issue by brentenebros** [rLoopTeam/website-v2#3]
need two new team lead members added:

Eoghan Kidney, Creative Media Lead, Ireland

Gregory Georgianna, Video Lead, USA

![eoghan_kidney_creative_media](https://cloud.githubusercontent.com/assets/13357722/13610913/f030e220-e52d-11e5-8d20-80501c7c205e.jpg)

![greg_georgianna_video](https://cloud.githubusercontent.com/assets/13357722/13610918/f6bbea40-e52d-11e5-9d8c-e142dcf2ee6e.jpg)

**Comment by gordon13** [comment]
Done
