### ISSUE TITLE
Team Member Section

### ISSUE THREAD

**Issue by brentenebros** [rLoopTeam/website-v2#4]
Would like to have active team members listed. If they submitted photos to folder (gdrive>rLoop>public relations>webdev>team headshots) they should get priority listing, then active members using their avatar image. @ariporad said this could be done? could go just below the existing team leads and 'join rLoop' button

**Comment by ariporad** [comment]
How do you define active?

**Comment by brentenebros** [comment]
Active Slack Account

Brent Lessard | rloop.org |

**Comment by UltraL0rd** [comment]
list updated, close please
