### ISSUE TITLE
Interactive Map

### ISSUE THREAD

**Issue by brentenebros** [rLoopTeam/website-v2#5]
would like to incorporate the interactive 'reach of rLoop' map that Jasper made somewhere, either in new page or in 'our team' page:

https://drive.google.com/open?id=0BwNfHq_1FTp6ZjNMdDVKcGQ5bTg

**Comment by UltraL0rd** [comment]
Will take a look at getting this in some time over the next 2 days

**Comment by UltraL0rd** [comment]
this has been done, but the map styling is seriously off (or i am missing something )
