### ISSUE TITLE
Pop-up causes the site to not be full-width

### ISSUE THREAD

**Issue by cxar** [rLoopTeam/website-v2#6]
Closing the pop-up reverts the site back to full-width.

**Comment by gordon13** [comment]
Fixed

**Comment by cxar** [comment]
I just checked, and it is still an issue

**Comment by gordon13** [comment]
Have you cleared your browser cache? I tried it on Chrome and Firefox, and the issue is gone

**Comment by cxar** [comment]
My apologies, it is indeed fixed

**Comment by gordon13** [comment]
Cool :)
