### ISSUE TITLE
add to press section

### ISSUE THREAD

**Issue by brentenebros** [rLoopTeam/website-v2#8]
please add the following to the press section:

Forbes article - Title: "Crowdsourcing the Hyperloop: How a Group of Redditors are Taking on Elon Musk's Challenge" - http://www.forbes.com/sites/jasonbelzer/2016/03/07/crowdsourcing-the-hyperloop-how-a-group-of-redditors-are-taking-on-elon-musk/#5e3bc7421de8

10xLabs interview - Title: "Hyperloop Makers Interview - rLoop, Founded Upon the Internet" - https://soundcloud.com/10xlabs/hyperloop-makers-interview-rloop

In the Loop interview - Title: "rLoop Interview with Brent and Tom" - https://www.youtube.com/watch?v=CyGA4ZRl2jQ

Techstuffed - Title: "Q&A with rLoop Project Manager Brent Lessard" - http://www.techstuffed.com/qa-rloop-project-manager-brent-lessard-pods-hyperloop-future/

TechAU - Title: "Help Fund the Future of Transport, rLoop Hyperloop Pod Hits IndieGoGo" - http://techau.com.au/help-fund-the-future-of-transport-rloop-hyperloop-pod-hits-indiegogo/

**Comment by gordon13** [comment]
Added new press articles
